"""create posh incident table

Revision ID: 63afc5b060cd
Revises: f34b4e2bb494
Create Date: 2026-09-21 11:23:40.224731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63afc5b060cd'
down_revision: Union[str, Sequence[str], None] = 'f34b4e2bb494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posh_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complainant_id', sa.Integer(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('respondent_name', sa.String(length=150), nullable=False),
    sa.Column('incident_date_period', sa.String(length=100), nullable=False),
    sa.Column('location_channel', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_files', sa.String(length=500), nullable=True),
    sa.Column('icc_case_officer_id', sa.Integer(), nullable=True),
    sa.Column('case_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['complainant_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['icc_case_officer_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posh_incidents_id'), 'posh_incidents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posh_incidents_id'), table_name='posh_incidents')
    op.drop_table('posh_incidents')
    # ### end Alembic commands ###
